### ISSUE TITLE
Support of PacBio reads

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#1]
Hi,
Do you have any plans to support PacBio reads?

Thank you in advance.

Mic

**Comment by lpryszcz** [comment]
Hi, Yes, I'm currently working on this, but it turned out to be slightly more complicated than I've anticipated. I should have something ready this autumn. Are you willing to test it?

**Comment by mictadlo** [comment]
Hi happy to test it when we got our PacBio data in few months. Will you support Illumina or/and PacBio?

**Comment by lpryszcz** [comment]
I want to support all sort of reads
- short reads are currently supported (Illumina, 454 and so on)
- support for long reads is under development (PacBio, Nanopore)

**Comment by lpryszcz** [comment]
Support to PacBio was added through pyScaf. Note, it's still experimental!
