### ISSUE TITLE
Run reduction only - no scaffolding libraries

### ISSUE THREAD

**Issue by thackl** [Gabaldonlab/redundans#10]
If I understand correctly, illumina libraries are not required for the reduction step. I am running redundans with `--noscaffolding --nogapclosing` because I want to scaffold the reduced assembly with PacBio data. However, redundans always seems to require `-i/--fastq` and than checks insert sizes for the libraries. Is there a way around that?

**Comment by lpryszcz** [comment]
try using `fasta2homozygous.py` instead of `redundans.py`. 

BTW: I'm planning to use depth of coverage in the reduction step in the future, this is why I'm asking for FastQ libraries to be provided anyway. Also, I'm planning to implement scaffolding with PacBio in the near future, so stay tuned :)

**Comment by thackl** [comment]
Yeah, at first I was thinking that you already use depth of coverage because you had the mapping first.

I will use fasta2homozygous.py directly, thx.

**Comment by mictadlo** [comment]
Hi @thackl,
What did you after the reduction step? Did you use PBjelly or PEP_Scaffolder?

Thank you in advance.

Michal
