### ISSUE TITLE
Test run fails (ends with IndexError: list index out of range)

### ISSUE THREAD

**Issue by aersoares81** [Gabaldonlab/redundans#10]
Hi folks, test run fails like this:

$./redundans.py -v -i test/*_?.fq.gz -o test/run.denovo
Options: Namespace(fasta='', fastq=['test/5000_1.fq.gz', 'test/5000_2.fq.gz', 'test/600_1.fq.gz', 'test/600_2.fq.gz'], identity=0.51, iters=2, joins=5, limit=0.2, linkratio=0.7, log=<open file '<stderr>', mode 'w' at 0x7fc0edf5a1e0>, longreads=[], mapq=10, mem=16, minLength=200, nocleaning=True, nogapclosing=True, norearrangements=False, noreduction=True, noscaffolding=True, outdir='test/run.denovo', overlap=0.8, reference='', resume=False, threads=4, tmp='/tmp', usebwa=False, verbose=True)
Traceback (most recent call last):
  File "./redundans.py", line 539, in <module>
    main()
  File "./redundans.py", line 527, in main
    _check_dependencies(dependencies)
  File "./redundans.py", line 443, in _check_dependencies
    curver = out.split()[-1]
IndexError: list index out of range

**Comment by lpryszcz** [comment]
Hi, what's your system? 

Can you try execute `type cat`?

Best,

**Comment by SvitlanaLukicheva** [comment]
Hello, I have exactly the same issue. Did you find a solution?

**Comment by SvitlanaLukicheva** [comment]
I found a solution by downloading the version 0.13c and installing it via INSTALL.sh. But impossible to make work the current version.

**Comment by lpryszcz** [comment]
There is [conda package](https://anaconda.org/genomedk/redundans) kindly created by [GenomeDK](https://genome.au.dk/)

``` 
conda install -c genomedk redundans
```

Nore, you will need Python2, thus Miniconda2 for Redundans. The Conda package lacks matplotlib, so if you want to get plots, install it separately

```
pip install matplotlib
```
