### ISSUE TITLE
Question about scaffolding / gap closing

### ISSUE THREAD

**Issue by SaelinB** [Gabaldonlab/redundans#101]
When scaffolding is done using paired reads, but --nogapclosing is set, are the resulting scaffolds only ones that overlap?

**Comment by Dfupa** [comment]
Hi @SaelinB,

Only adjacent contigs connected by at least 5 (default value of the parameter` -j,  --joins` in the script) read pairs are joined through SSPACE3 as scaffolds. Setting ` --nogapclosing`, no further action is done to fill the gaps before the final reduction step.

Let me know if this answers your question!

**Comment by SaelinB** [comment]
Thanks for your response! 

I'm a little new to this, and I guess I'm a bit confused as to exactly what gapclosing is doing. I saw that after using redundans normally and with --nogapclosing, both scaffolds.fa and scaffolds.reduced.fa have gaps as Ns of variable lengths. So, how are these Ns different between scaffolds.fa/scaffolds.reduced.fa with or without gapclosing? and when gapclosing is on, how are the Ns different between scaffolds.fa, scaffolds.filled.fa and scaffold.reduced.fa?

**Comment by Dfupa** [comment]
Hi @SaelinB,

Redundans uses _**GapCloser**_ from SOAP denovo to close the gaps emerging during the scaffolding process. It utilizes the paired end reads and remaps them to the scaffolds. If one end of the read is paired to a gap and the other read is paired to a scaffold, It will try to use the read sequences to try and reconstruct the gap sequence. Keep in mind that for gap closure, **sufficient sequencing depth of each insert-sized library can significantly enhance the effectiveness of filling gaps of corresponding sizes.**.

After each step of reduction, scaffolding, gap closing, etc., the number of 'N's can change. This can occur by removing chunks of heterozygous contigs, generating new gaps during the scaffolding or filling gaps with high-quality sequences. These changes often lead to a decrease in the number of 'N's at the later steps, although this isn't always the case. It's worth noting that you can employ other metrics to assess the assembly quality such as  improvements in the N50, longer contig sizes, fewer total contigs, and a higher percentage of homozygous contigs. So, **while the presence of 'N's is informative, there are additional metrics that can assist in evaluating genome assembly quality both before and after the process.**

Hope this answer is informative!

**Comment by SaelinB** [comment]
Okay thanks for the explanation!

**Comment by Dfupa** [comment]
@SaelinB Glad it helped

If you don't mind, I'll close this issue for now, if you ever need it to be reopened, just comment on it
