### ISSUE TITLE
conda install error

### ISSUE THREAD

**Issue by maxmaronna** [Gabaldonlab/redundans#103]
Hello,
I am trying to install and test redundans (conda mode). I created and activated the env as stated; once I tried to install redundans, I got this message:

(redundans) [maxmaronna@access2 ~]$ conda install -c bioconda redundans
Fetching package metadata .............
Solving package specifications:

PackageNotFoundError: Packages missing in current channels:

  - redundans -> gfastats >=1.3.6 -> libgcc-ng >=12
  - redundans -> gfastats >=1.3.6 -> libstdcxx-ng >=12
  - redundans -> gfastats >=1.3.6 -> libzlib >=1.2.13,<1.3.0a0
  - redundans -> matplotlib-base >=3.7.3
  - redundans -> meryl 1.3.*
  - redundans -> miniasm >=0.3 -> zlib >=1.2.13,<1.3.0a0
  - redundans -> minimap2 >=2.24
  - redundans -> numpy >=1.24.0 -> mkl >=2023.1.0,<2024.0a0 -> intel-openmp 2023.*
  - redundans -> numpy >=1.24.0 -> numpy-base 1.24.3 py310hb5e798b_1
  - redundans -> numpy >=1.24.0 -> libopenblas >=0.3.20,<1.0a0
  - redundans -> perl >=5.32.1,<5.33.0a0 *_perl5 -> libnsl >=2.0.0,<2.1.0a0
  - redundans -> python_abi 3.10.* *_cp310
  - redundans -> r-base >=4 -> gcc_linux-64 11.2.0.* -> gcc_impl_linux-64 11.2.0.* -> libgcc-devel_linux-64 11.2.0 h1234567_0 -> __glibc >=2.17,<3.0.a0
  - redundans -> r-base >=4 -> gfortran_linux-64 11.2.0.* -> gfortran_impl_linux-64 11.2.0.*
  - redundans -> r-base >=4 -> gxx_linux-64 11.2.0.* -> gxx_impl_linux-64 11.2.0.*
  - redundans -> r-ggplot2 >=3.3.2 -> r-rlang >=0.4.10
  - redundans -> r-ggplot2 >=3.3.2 -> r-lifecycle >1.0.1
  - redundans -> r-ggplot2 >=3.3.2 -> r-vctrs >=0.5.0
  - redundans -> snap-aligner >=2.0.3

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

Any ideas to resolve this issue?
Best
max

**Comment by Dfupa** [comment]
Hi @maxmaronna,

Can you confirm whether you tried to install redundans through conda in a macOS system? Currently only the Linux OS and 64 architecture is supported, though in a future release we are contemplating providing support to macOS too. I attach my testing on a brand new instance of Ubuntu in a VM.


![image](https://github.com/Gabaldonlab/redundans/assets/43205584/8f8657b1-307f-45ed-a4b7-8d8e6ad3321d)

**Comment by maxmaronna** [comment]
Hello Diego,
I tried in a HPC cluster running AlmaLinux, conda 4.3.30. 
+ info: https://www.ncc.unesp.br/gridunesp/docs/v2/index.html

Saludos,
max

**Comment by Dfupa** [comment]
Hi @maxmaronna,

I am not able to reproduce this issue on any of my settings. Have you checked you got conda-forge and bioconda in the priority channels? Could you upgrade the conda version and try again?

**Comment by maxmaronna** [comment]
Hello Diego,
Unfortunatly I cannot change the conda config in this server. I tried the singularity option and I got this message:

singularity pull library://cgenomics/redundans/redundans

FATAL:   While pulling library image: error fetching image: image does not exist in the library: cgenomics/redundans/redundans:latest (amd64)

Then, I tried the docker and it was installed ok  :) I will test the docker config in a few days (and I will update this message).

Saludos y gracias,
max

**Comment by Dfupa** [comment]
Hi Max,

Thank you for bringing up to my attention the issue with singularity. Apparently it is incorrect on the main README file which I've adressed in this [commit](https://github.com/Gabaldonlab/redundans/commit/aca11f1dffa86be4f0352aa3b0d6270fc382a41d) , you can pull it using the following commands for v2.0

`singularity pull --arch amd64 library://cgenomics/redundans/redundans:2.0`

or 

`singularity pull --arch amd64 library://cgenomics/redundans/redundans:sha256.1526807bfbb14d696cfaff3644fdf69a39c480ce1b2f6b6fb5c0bc78a8527240`

Glad you are able to bypass it through the docker image. Regarding conda, I suspect it is a conda version / channel priority issue, as it might not be available for older conda versions but I have yet to verify it...

**Comment by maxmaronna** [comment]
Hello Diego,

Happy to help, the (new) link is working perfectly :) 
No problem about the conda, I will use the local install (or the singularity option). 
Thanks for your help and feedback!

Saludos,
max
