### ISSUE TITLE
Conda install issue

### ISSUE THREAD

**Issue by ALongmuir12** [Gabaldonlab/redundans#108]
Possible issue with conda instructions that might need a quick fix...

I tried to install following the Official conda package install instructions where it specifics python v3.8. My install errored because the python version did not match the package requirements

![image](https://github.com/Gabaldonlab/redundans/assets/153482327/bb4a70b3-a2df-4288-956e-835d304ac3ae)

I was able to fix this by updating python in the environment and install redundans again

conda install python=3.10
conda install -c bioconda redundans

The install instructions just might need an edit - hope this helps other people if they have trouble

**Comment by Dfupa** [comment]
Hi @ALongmuir12 ,

Indeed, this is an oversight on my side. When I was updating the bioconda recipe originally I intended it for Python >=3.8 and <3.11:

![image](https://github.com/Gabaldonlab/redundans/assets/43205584/3bc9825e-6f0b-47a5-a680-552f85b060dc)

However, during the bioconda-recipes build debug process I noticed that some of the python based modules (numpy, matplotlib) required a 3.10 version, but I forgot to update the readme with this information. Thanks for letting me now, I'll edit the readme and keep it in mind for future updates of the recipe.
