### ISSUE TITLE
lastal: can't interpret TAB

### ISSUE THREAD

**Issue by apelin20** [Gabaldonlab/redundans#11]
Hello,

Ran into this error:

@BioPower3-IBM ~/programs/redundans $ ./redundans.py -v -i /shared/reads/Pseudoloma/GDR-24_R*_trim100.fastq -f ~/Pseudoloma/reads/mira_merged_sample50X_try1_out.unpadded_above500.fasta -o test/Pseudo_mira_100bp_Scaffold_try1 --sspacebin ~/programs/SSPACE-STANDARD-3.0_linux-x86_64/SSPACE_Standard_v3.0.pl -t 8
Options: Namespace(fasta='/home/adrian/Pseudoloma/reads/mira_merged_sample50X_try1_out.unpadded_above500.fasta', fastq=['/shared/reads/Pseudoloma/GDR-24_R1_trim100.fastq', '/shared/reads/Pseudoloma/GDR-24_R2_trim100.fastq'], identity=0.51000000000000001, iters=2, joins=5, limit=0.20000000000000001, linkratio=0.69999999999999996, log=<open file '<stderr>', mode 'w' at 0x7f84863ad1e0>, mapq=10, minLength=200, nocleaning=True, nogapclosing=True, noreduction=True, noscaffolding=True, outdir='test/Pseudo_mira_100bp_Scaffold_try1', overlap=0.66000000000000003, sspacebin='/home/adrian/programs/SSPACE-STANDARD-3.0_linux-x86_64/SSPACE_Standard_v3.0.pl', threads=8, verbose=True)
 Aligning 3594477 mates per library...
Insert size statistics              Mates orientation stats
FastQ files median  mean    stdev   FF  FR  RF  RR
/shared/reads/Pseudoloma/GDR-24_R1_trim100.fastq /shared/reads/Pseudoloma/GDR-24_R2_trim100.fastq   264 265.46  14.71   1   9985    13  1
###### 

[Sat Mar 26 14:51:11 2016] Reduction...
# file name  genome size contigs heterozygous size   [%] heterozygous contigs    [%] identity [%]    possible joins  homozygous size [%] homozygous contigs  [%]

**lastal: can't interpret: TAB**
test/Pseudo_mira_100bp_Scaffold_try1/contigs.fa 17972387    5935    0   0.00    0   0.00    0.000   0   17972387    100.00  5935    100.00
 Aligning 3594477 mates per library...
###### 

[Sat Mar 26 14:51:40 2016] Scaffolding...
 iteration 1.1 ...

It doesn't look like it removed redundancies. Any idea what is causing this?
Adrian

**Comment by lpryszcz** [comment]
which version of LAST are you using (lastal --version)? 
I guess you need to update your LAST installation to version 700+.

**Comment by shyamrallapalli** [comment]
Yes it is an issue with LAST version, 
in earlier version example 581-f uses different options
`-f: output format: 0=tabular, 1=maf (1)`
so lastal was not performed at all, it exits by printing
`lastal: can't interpret: TAB`

so i suggests couple of points 
@lpryszcz could you please 
1. indicate version of the softwares you recommend installing in README
2. implement some exception raising to alert such issues

**Comment by lpryszcz** [comment]
@shyamrallapalli I have included version in README. implementing exception raising will take a bit more time...

**Comment by shyamrallapalli** [comment]
nice 👍 
and congratulations for the manuscript

**Comment by lpryszcz** [comment]
I have implemented LASTal version checking in the latest commit.
