### ISSUE TITLE
Please make the installation relocatable

### ISSUE THREAD

**Issue by eburgueno** [Gabaldonlab/redundans#14]
While I appreciate the automation provided with `INSTALL.sh`, it assumes several things:
- You're installing for your own user only.
- You're installing in your home directory.
- All required libraries are present.
- None of the dependencies are installed already.

In a typical HPC environment multiple users want to use a single installation of the same tool in multiple servers, typically on a shared volume over NFS or similar. Most of them also implement dynamic management of environment variables through Environment Modules, rather than relying on `~/.bashrc`. or the like.

Why not providing a standard `./configure` and `Makefile` to allow system administrators to relocate where to install (via `--prefix`)?
Alternatively, you could let the end user install the dependencies himself but still check for their presence in the environment PATH (the way you do now after compiling them).

Thanks

**Comment by lpryszcz** [comment]
[Manual installation](https://github.com/lpryszcz/redundans#manual-installation) is recommended for advanced users - simply you can configure all dependencies as you wish. Unfortunately, I have more urgent things than developing one-fit-all installer... I'll be happy to include it if you wish to develop it ;)
