### ISSUE TITLE
How will redundans perform on allopolyploid plants?

### ISSUE THREAD

**Issue by davidries84** [Gabaldonlab/redundans#14]
I'm planning on using redundans on an allopolyploid plant (brassica napus), using paired-end reads and the available reference sequence. My main concern is, that redundans will remove homologous contigs
from the two subgenomes, due to their high similarity. But these contigs are not heterozygous regions, but real, albeit similar, different genomic regions. I guess this could be accounted for by read coverage?
Does redundans attempt to deal with this correctly?

Best,

David

**Comment by lpryszcz** [comment]
Hi David, you could try it. Maybe first run reduction (bin/fasta2homozygous.py) just to estimate what's expected divergence between subgenomes (check contigs.reduced.fa.hist.png). If you know the divergence between subgenomes, just set `--identity` to larger value than expected divergence. 
Let me know how it worked!
Bests,
