### ISSUE TITLE
PacBio scaffolding: stats issues and excess Ns insertions

### ISSUE THREAD

**Issue by bifxcore** [Gabaldonlab/redundans#18]
I ran redundans with the --longreads option followed by the names of 13 PacBio fastq files.

The log appears to have some misleading numbers:
- scaffolds.longreads.fa has exactly the same stats in all columns as the last (13th)  fastq file.
- scaffolds.reduced.fa has the same value for "longest" as the last fastq file.

The original genome supplied with '--fasta' only had 25 Ns. Now the scaffolds.reduced.fa contains over half a million Ns. That's 13% of the genome. Is this a known issue?

**Comment by lpryszcz** [comment]
Thanks for the issue report, I'll keep it in mind while working on the method update.
