### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ptranvan** [Gabaldonlab/redundans#24]
Hi,

1) I'm not sure to understand how redundans works. 
a) For 2 contig of the same lengths: it makes a consensus: ok
b) For contigs with different lengths: does it makes a consensus of the longest as a seed ?

2) Can redundans be applied to scaffolds instead of contigs ?

**Comment by lpryszcz** [comment]
Hi, 

1) No, redundans clusters the contigs having enought overlap / identity, keep the longest as homozygous and removes the rest. There is no consensus generated. 
2) Yes, but note that scaffolds may be affected by mis-assemblies. This is especially common problem in heterozygous genome assembly. Plus, large number of gaps complicates reduction step. 
I would recommend trying redundans with both, contigs and scaffolds and compare the results. 

Hope it helps!

**Comment by ptranvan** [comment]
Thanks for your support.

In case where the 2 contigs have the same lengths ? Do you pick one randomly or just leave it

**Comment by lpryszcz** [comment]
then one is picked up randomly.
