### ISSUE TITLE
reduce Pacbio assembly ?

### ISSUE THREAD

**Issue by ptranvan** [Gabaldonlab/redundans#25]
Hi,

I have a fasta file after a pacbio assembly. I would like to run redundans but only the reducing option (no scaffolding and no gapclosing) with that command:

`redundans.py -i reads.fastq -f assembly.fasta -o output --identity 0.9 --overlap 0.9 --minLength 200 --noscaffolding --nogapclosing -t 10 2> redundans.log`

Does it work with pacbio ? does redundans need the input files (-i) when only the reduced option is applied ?

**Comment by lpryszcz** [comment]
You can try above or run reduction module instead:
`fasta2homozygous.py -i contigs.fa -t 4`

**Comment by mictadlo** [comment]
Hi @ptranvan,
What did you after the reduction step? Did you use PBjelly or PEP_Scaffolder?

Thank you in advance.

Michal

**Comment by lpryszcz** [comment]
Hi Michal, you can use Redundans long-read scaffolder (don't specify --noscaffolding option) or use any of alternative long-read scaffolders ie. SSPACE longread
