### ISSUE TITLE
Maximum sequences limited to 327068

### ISSUE THREAD

**Issue by aseetharam** [Gabaldonlab/redundans#26]
For redundans is there a upper limit of sequences that can be stored (first step). I have few assemblies that have more than 327,068 contigs, but by default redundans only reads the above mentioned scaffolds for processing. 

Thanks for any input!

**Comment by lpryszcz** [comment]
Hi, there is no limit for number of contigs, however Redundans will ignore contigs shorter than 200 bp (`--minLength 200`), as these bring very little information, while complicating reduction/scaffolding. Resulting small gaps ie 200bp can be easily closed later.
