### ISSUE TITLE
bioconda package for redundans

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#27]
Hi, 
Were you able to create a [bioconda](https://github.com/bioconda/bioconda-recipes) package for redundans?

Thank you in advance.

Best wishes,

Michal

**Comment by lpryszcz** [comment]
I'll look into it. Currently I'm working [on update](https://github.com/lpryszcz/redundans/tree/make), where installation is rather trivial, so I guess there won't be any need for conda support.

**Comment by mictadlo** [comment]
Galaxy (usegalaxy.org) will dependent on Bioconda. I think it would good to have your software in Galaxy.

**Comment by Rob-murphys** [comment]
What about for those of us who use conda based clusters?

**Comment by lpryszcz** [comment]
Any help with that? 
I thought about conda, but have no experience. 
Galaxy is totally new thing for me... Anyone?
