### ISSUE TITLE
error:  unrecognized arguments:  /mnt/md1/REFERENCE.fa

### ISSUE THREAD

**Issue by robalba1** [Gabaldonlab/redundans#29]
I would like to try a reference-guided assembly to compare with my de novo assembly. 

I am doing something wrong and would like any guidance that you can offer.

My command is:
/home/rob/src/redundans/redundans.py -v -i Pcri_800bp_12repaired_R1.fastq Pcri_800bp_12repaired_R2.fastq Pcri_3kb_12repaired_R1.fastq Pcri_3kb_12repaired_R2.fastq Pcri_5kb_12repaired_R1.fastq Pcri_5kb_12repaired_R2.fastq Pcri_10kb_12repaired_R1.fastq Pcri_10kb_12repaired_R2.fastq Pcri_470bp_40pct_R1.fastq Pcri_470bp_40pct_R2.fastq -r /mnt/md1/Mguttatus.fa -f /mnt/md1/redundans_1Kcut_u.5_iden0.91/scaffolds.filled.fa -o /mnt/md1/redundans_1Kcut_u.5_iden0.90_overlap0.66_REF --noscaffolding --threads 80 --identity 0.90 --overlap 0.66 --minLength 1000 --mapq 15 --iters 4 --sspacebin /home/rob/src/SSPACE/SSPACE_Standard_v3.0.pl

Which throws the following error:
redundans.py: error: unrecognized arguments: /mnt/md1/Mguttatus.fa

Mguttatus.fa is the fasta file for the reference assembly.

Why does it not recognize my Mguttatus.fa file?

Rob

**Comment by lpryszcz** [comment]
I guess you are using old version (before 0.14)... you can check which version you are using with `./redundans.py --version`

the best if you update to the newest version:
```
git clone --recursive https://github.com/lpryszcz/redundans.git
cd redundans
(cd bin/bwa && make clean && make)
(cd bin/last && make clean && make)
(cd bin/snap && make clean && make)
```

**Comment by robalba1** [comment]
It looks like this URL is linked to the old version 0.13.
https://github.com/lpryszcz/redundans.git

Am I missing something obvious?

Thank you Leszek.

Rob

**Comment by lpryszcz** [comment]
not really, it points to the latest version. 
you need to update. the best is to do a fresh install.
