### ISSUE TITLE
Canu assebly (PacBio)

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#30]
Hi,
I have got a PacBio assembly produced by Canu. It has created 3 output files (`BAFB.contigs.fasta`, `BAFB.unassembled.fasta`, `BAFB.unitigs.fasta`). The meaning of the output files is described [here](https://github.com/marbl/canu/issues/286#issuecomment-258876724). 

Which of the files should I use for redundans?

Thank you in advance.

Michal

**Comment by lpryszcz** [comment]
This is the question for Canu developers. You should provide Redundans with contigs / scaffolds and short/long-reads and/or reference genome as described in the main page.
