### ISSUE TITLE
Bug: automake-1.15 needed

### ISSUE THREAD

**Issue by pcarbo** [Gabaldonlab/redundans#33]
Regarding your installation instructions:

```bash
(cd bin/parallel && make clean && ./configure && make)
```

I believe `make clean` should be after the `configure` command.

Additionally, for some reason your configure script inside `bin/parallel` is requiring the exectable `automake-1.15` instead of `automake`. It is important that we use specifically version 1.15 of automake? If not, perhaps you can fix this? My current workaround is to create a symbolic link `ln -s /bin/automake automake-1.15`.

**Comment by lpryszcz** [comment]
Right, the problem is because make clean doesn't clean up automake config from my local machine and after commiting it gets updated. It should be solved now (I've pushed fresh parallel repo).

**Comment by pcarbo** [comment]
Thanks!
