### ISSUE TITLE
fasta2homozygous.py error

### ISSUE THREAD

**Issue by mgalland** [Gabaldonlab/redundans#35]
Dear Leszek, 
Your Redundans assembly pipeline looks very promising. Unfortunately I got stuck when running the test run: 

`./redundans.py -v -i test/*.fq.gz -f test/contigs.fa -o test/run1`

I got the following error message:
` File "/home/mgalland/workspace/wild_tomato_genomes/scr/redundans/bin/fasta2homozygous.py", line 126
    contig2skip = {c: 0 for c in faidx} `
`SyntaxError: invalid syntax`

The `for`looks like the problem here.

Can you help there? 
Thanks in advance,
Marc

**Comment by lpryszcz** [comment]
You need to use Python 2.7 (most likely you are running python 2.6). 

Bests,

**Comment by lpryszcz** [comment]
I've added exception for Python versions other than 2.7.
