### ISSUE TITLE
confusion with contigs.reduced.fa.hetero.tsv file

### ISSUE THREAD

**Issue by PedroBarbosa** [Gabaldonlab/redundans#36]
Hello,

I've tried redundans before, but now I need it for a different purpose, so I downloaded latest version.

I suppose that the info displayed in first column of this auxiliar file represents all the contigs that were removed that fit the --identity and --overlap criteria.  I confirmed that by observing their absence in the contigs.reduced.fa file. My doubt lies on those longer contigs represented in column 3. I see that not all of them are represented in the final reduction fasta file, which means that those that are the longer representation of some contigs in column 1, are also the shorter representation of some contigs in column 3, thus they also get removed. Is that right?

Just want to clear this out, before I proceed with my analysis.
Thanks in advance,
Pedro

**Comment by lpryszcz** [comment]
Yes, precisely.
