### ISSUE TITLE
Not multiprocessing?

### ISSUE THREAD

**Issue by jwasmuth** [Gabaldonlab/redundans#37]
Hi,
This didn't seem to have been covered before. I'm running redundans with '-t 32' yet when I do a 'htop' to look at the processor usages, I see 32 instances of lastal being put through one processor. So they are being threaded through the one processor.

![image](https://user-images.githubusercontent.com/7673886/30082696-f6f6669c-9248-11e7-93fc-39800cd30b28.png)

I did some speed tests with -t2 and -t32 and got no improvement in run time. I've tried two different systems with different linux os. Same problem.

When I run the lastal command at the commandline, I see the expected behaviour. My python skills are not particularly strong. I spoke with a colleague who said that getting python to run multiprocessor jobs can be a pain. Is there a problem?

Thanks

James

**Comment by jwasmuth** [comment]
Sorry - I posted to wrong distribution.

**Comment by lpryszcz** [comment]
https://github.com/Gabaldonlab/redundans/issues/8
