### ISSUE TITLE
Use for iontorrent data

### ISSUE THREAD

**Issue by biocyberman** [Gabaldonlab/redundans#38]
I want to modify this to use for iontorrent data. Should I do that or it is a no-go because some dependencies work only with paired-end data?

**Comment by lpryszcz** [comment]
hmm, what's the profit of iontorrent? slightly longer reads? I don't think it'll improve the assembly much as only very small gaps will be closed... I'd rather discourage you from wasting time...

**Comment by biocyberman** [comment]
Thanks for giving me a definite answer :) 
Illumina data is not an option for me at the moment, iontorrentdata is what I get. So the purpose of adaptation for iontorrent data is not to generalize it for public use, but rather to solve our own problem. 

Just so you know, I was testing `pyScaf` and found about `redundans`. I went ahead and run `redundans` on iontorrent data (and `SPAdes` output) to test the reduction and scaffolding features.  I am checking the output.

**Comment by lpryszcz** [comment]
right, you can still use redundans to remove heterozygous regions and try to use iontorrent data as long reads, although I won't expect much of an improvement. anyway, let me know how it went :) 
for discussion, please use https://groups.google.com/forum/#!forum/redundans
bests!
