### ISSUE TITLE
subprocess error

### ISSUE THREAD

**Issue by gucascau** [Gabaldonlab/redundans#39]
Hi all, I am working on a polymorphic genome, and tried to use this software. But after installing everything, I kept getting the following error when using the test data. I am not sure what is the reason. Can anyone help me to solve this problem? Thank you so much.

Traceback (most recent call last):
  File "./redundans.py", line 521, in <module>
    main()
  File "./redundans.py", line 516, in main
    o.norearrangements, o.verbose, o.log)
  File "./redundans.py", line 315, in redundans
    libraries = get_libraries(fastq, lastOutFn, mapq, threads, verbose, log)
  File "./redundans.py", line 62, in get_libraries
    genomeFrac, stdfracTh, maxcfracTh)
  File "/home/xinw/software/redundans/bin/fastq2insert_size.py", line 189, in fastq2insert_size
    isstats = get_isize_stats(fq1, fq2, fasta, mapq, threads, limit, verbose, stdfracTh, maxcfracTh)
  File "/home/xinw/software/redundans/bin/fastq2insert_size.py", line 111, in get_isize_stats
    aligner = _get_snap_proc(fq1, fq2, fasta, threads, verbose, alignerlog)
  File "/home/xinw/software/redundans/bin/fastq2sspace.py", line 133, in _get_snap_proc
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=log)
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by lpryszcz** [comment]
Hi, Can you list the content of output dir `ls -lah` and write me exact command?

**Comment by mzinkgraf** [comment]
I am getting the same error. Below are are the command and outputs.
Thanks for your help

redundans zinkgrm$ ./redundans.py -v -i test/*.fq.gz -f test/contigs.fa -o test/run1
Options: Namespace(fasta='test/contigs.fa', fastq=['test/5000_1.fq.gz', 'test/5000_2.fq.gz', 'test/600_1.fq.gz', 'test/600_2.fq.gz', 'test/pacbio.fq.gz'], identity=0.51, iters=2, joins=5, limit=0.2, linkratio=0.7, log=<open file '<stderr>', mode 'w' at 0x10f9811e0>, longreads=[], mapq=10, minLength=200, nocleaning=True, nogapclosing=True, norearrangements=False, noreduction=True, noscaffolding=True, outdir='test/run1', overlap=0.8, reference='', resume=False, threads=4, verbose=True)

##################################################
[Fri Dec  8 09:36:31 2017] Reduction...
#file name	genome size	contigs	heterozygous size	[%]	heterozygous contigs	[%]	identity [%]	possible joins	homozygous size	[%]	homozygous contigs	[%]
test/run1/contigs.fa	163897	245	66377	40.50	221	90.20	94.854	0	97520	59.50	24	9.80

##################################################
[Fri Dec  8 09:36:34 2017] Estimating parameters of libraries...
 Aligning 19504 mates per library...
Insert size statistics				Mates orientation stats
FastQ files	read length	median	mean	stdev	FF	FR	RF	RR
Traceback (most recent call last):
  File "./redundans.py", line 521, in <module>
    main()
  File "./redundans.py", line 516, in main
    o.norearrangements, o.verbose, o.log)
  File "./redundans.py", line 315, in redundans
    libraries = get_libraries(fastq, lastOutFn, mapq, threads, verbose, log)
  File "./redundans.py", line 62, in get_libraries
    genomeFrac, stdfracTh, maxcfracTh)
  File "/Users/zinkgrm/Documents/scripts/redundans/bin/fastq2insert_size.py", line 189, in fastq2insert_size
    isstats = get_isize_stats(fq1, fq2, fasta, mapq, threads, limit, verbose, stdfracTh, maxcfracTh)
  File "/Users/zinkgrm/Documents/scripts/redundans/bin/fastq2insert_size.py", line 111, in get_isize_stats
    aligner = _get_snap_proc(fq1, fq2, fasta, threads, verbose, alignerlog)            
  File "/Users/zinkgrm/Documents/scripts/redundans/bin/fastq2sspace.py", line 133, in _get_snap_proc
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=log)
  File "/Users/zinkgrm/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/zinkgrm/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

redundans zinkgrm$ ls -lah test/run1/
total 1200
drwxr-xr-x  17 zinkgrm  staff   578B Dec  8 09:36 .
drwxr-xr-x  14 zinkgrm  staff   476B Dec  8 09:36 ..
lrwxr-xr-x   1 zinkgrm  staff    58B Dec  8 09:36 contigs.fa -> /Users/zinkgrm/Documents/scripts/redundans/test/contigs.fa
-rw-r--r--   1 zinkgrm  staff    23K Dec  8 09:36 contigs.fa.bck
-rw-r--r--   1 zinkgrm  staff   8.7K Dec  8 09:36 contigs.fa.des
lrwxr-xr-x   1 zinkgrm  staff    62B Dec  8 09:36 contigs.fa.fai -> /Users/zinkgrm/Documents/scripts/redundans/test/contigs.fa.fai
-rw-r--r--   1 zinkgrm  staff   475B Dec  8 09:36 contigs.fa.prj
-rw-r--r--   1 zinkgrm  staff   984B Dec  8 09:36 contigs.fa.sds
-rw-r--r--   1 zinkgrm  staff   984B Dec  8 09:36 contigs.fa.ssp
-rw-r--r--   1 zinkgrm  staff   121K Dec  8 09:36 contigs.fa.suf
-rw-r--r--   1 zinkgrm  staff   160K Dec  8 09:36 contigs.fa.tis
-rw-r--r--   1 zinkgrm  staff    98K Dec  8 09:36 contigs.reduced.fa
-rw-r--r--   1 zinkgrm  staff    29K Dec  8 09:36 contigs.reduced.fa.0.05
-rw-r--r--   1 zinkgrm  staff   270B Dec  8 09:36 contigs.reduced.fa.0.05.log
-rw-r--r--   1 zinkgrm  staff   1.7K Dec  8 09:36 contigs.reduced.fa.fai
-rw-r--r--   1 zinkgrm  staff   6.9K Dec  8 09:36 contigs.reduced.fa.hetero.tsv
-rw-r--r--   1 zinkgrm  staff   106K Dec  8 09:36 contigs.reduced.fa.hist.png
redundans zinkgrm$

**Comment by lpryszcz** [comment]
can you make sure `snap-aligner` is correctly installed? There should be executable in `REDUNDANS_SRC/bin/snap`. It there isn't, try to compile it: `cd bin/snap && make clean && make`

**Comment by lpryszcz** [comment]
Alternatively, update to the latest version and try again. If it fails, you can run it with **-b** which will use BWA instead of snap-aligner.

```
git clone --recursive https://github.com/lpryszcz/redundans.git
cd redundans && bin/.compile.sh
```
