### ISSUE TITLE
the position of the original contigs on the final output

### ISSUE THREAD

**Issue by Hazelhuangup** [Gabaldonlab/redundans#41]
Dear colleague, Is there a file like .agp that specify the position of the original contigs on the final output?

**Comment by lpryszcz** [comment]
No, Redundans relies on numerous intermediate programmes so no .agp is created. If there is enough interest I can write some function to map original contigs onto final assembly. Will it be very useful? Maybe there are such solutions already?

**Comment by Hazelhuangup** [comment]
Thank you for your reply. Mapping contigs to final assembly might be applicable, but I think it won't do any help to other users. I just run sspace separately and I got what I want anyway.
