### ISSUE TITLE
Unix install failure

### ISSUE THREAD

**Issue by milw** [Gabaldonlab/redundans#44]
I ran the suggested unix install command (on Ubuntu 16.04) and got install error from Lastal:

'
Redundans and its dependencies will be installed in: /media/data/software/redundans

Installation will take 5-10 minutes.
To track the installation status execute in the new terminal:
  tail -f /media/data/software/redundans/install.log

 Do you want to proceed with installation (y/n)? y

Fri Feb 23 08:41:57 CST 2018 Checking dependencies...
 Everything looks good :) Let's proceed...
Fri Feb 23 08:41:57 CST 2018 Downloading Redundans...
Fri Feb 23 08:41:58 CST 2018 Updating submodules...
Fri Feb 23 08:41:59 CST 2018 Compiling dependencies...
 === You can find log in: /media/data/software/redundans/install.log ===
 I'll use 63 thread(s) for compiling
Fri Feb 23 08:41:59 CST 2018  BWA
Fri Feb 23 08:42:04 CST 2018  LASTal
  [2] ERROR!
       ^
lastal.cc:761:33: error: no matching function for call to ‘cbrc::Alignment::makeXdrop(cbrc::Centroid&, cbrc::GreedyXdropAligner&, bool&, const uchar*&, const uchar*&, int&, const int (*&)[64], int&, cbrc::GeneralizedAffineGapCosts&, int&, int&, size_t&, const int (*&)[64], const cbrc::TwoQualityScoreMatrix&, const uchar*&, const uchar*&, cbrc::Alphabet&, cbrc::AlignmentExtras&, double&, int&)’
     args.gamma, args.outputType );
                                 ^
lastal.cc:761:33: note: candidate is:
In file included from AlignmentPot.hh:8:0,
                 from lastal.cc:16:
Alignment.hh:80:8: note: void cbrc::Alignment::makeXdrop(cbrc::GappedXdropAligner&, cbrc::Centroid&, const uchar*, const uchar*, int, const int (*)[64], int, const cbrc::GeneralizedAffineGapCosts&, int, int, size_t, const int (*)[64], const cbrc::TwoQualityScoreMatrix&, const uchar*, const uchar*, const cbrc::Alphabet&, cbrc::AlignmentExtras&, double, int)
   void makeXdrop( GappedXdropAligner& aligner, Centroid& centroid,
        ^
Alignment.hh:80:8: note:   candidate expects 19 arguments, 20 provided
lastal.cc: In function ‘void eraseWeakAlignments(LastAligner&, cbrc::AlignmentPot&, size_t, char, const uchar*)’:
lastal.cc:775:12: error: ‘struct cbrc::Alignment’ has no member named ‘hasGoodSegment’
     if (!a.hasGoodSegment(dis.a, dis.b, args.minScoreGapped, dis.m, gapCosts,
            ^
makefile:100: recipe for target 'lastal.o8' failed
make[1]: *** [lastal.o8] Error 1
make[1]: Leaving directory '/media/data/software/redundans/bin/last/src'
makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
'

**Comment by lpryszcz** [comment]
Can you try with the latest push? I've updated lastal version. The best just clone the repo from scratch
```
git clone --recursive https://github.com/lpryszcz/redundans.git
cd redundans && bin/.compile.sh

```
