### ISSUE TITLE
redundans failed

### ISSUE THREAD

**Issue by SolayMane** [Gabaldonlab/redundans#45]
Dear all,

I launched the following script to assist my assembly with redundans :

#!/bin/bash
redundans.py -i /home/raw/S04[56]_[12].trimmed.fastq -f /home/contig_k116.fasta -o /data_sra_home/scaffolding_redundans/run1/ -t 40 --resume -m 200 -l /data_sra_home/scaffolding_redundans/SR_subset_1K.fa

 bellow is the screenshot of my terminal after the failed attempt :
##################################################
[Sun Mar 18 10:18:32 2018] Resuming previous run from /data_sra_home/scaffolding_redundans/run1/...
[WARNING] numpy or matplotlib missing! Cannot plot histogram
/data_sra_home/scaffolding_redundans/run1/contigs.fa    665152391       83469  141609580        21.29   42509   50.93   88.051  0       523542811       78.71  40960    49.07
Insert size statistics                          Mates orientation stats
FastQ files     read length     median  mean    stdev   FF      FR      RF     RR
Traceback (most recent call last):
  File "/home1/software/redundans/redundans.py", line 539, in <module>
    main()
  File "/home1/software/redundans/redundans.py", line 534, in main
    o.norearrangements, o.verbose, o.usebwa, o.log, o.tmp)
  File "/home1/software/redundans/redundans.py", line 321, in redundans
    libraries = get_libraries(fastq, lastOutFn, mapq, threads, verbose, log, usebwa=usebwa)
  File "/home1/software/redundans/redundans.py", line 61, in get_libraries
    libdata = fastq2insert_size(log, fastq, fasta, mapq, threads, limit/100, genomeFrac, stdfracTh, maxcfracTh, usebwa=usebwa)
  File "/home1/software/redundans/bin/fastq2insert_size.py", line 191, in fastq2insert_size
    isstats = get_isize_stats(fq1, fq2, fasta, mapq, threads, limit, verbose, stdfracTh, maxcfracTh)
  File "/home1/software/redundans/bin/fastq2insert_size.py", line 124, in get_isize_stats
    rname, flag, chrom, pos, mapq, cigar, mchrom, mpos, isize, seq = sam.split('\t')[:10]
ValueError: need more than 1 value to unpack

thank you for your help to raise this issue!

**Comment by lpryszcz** [comment]
Have you tried running test dataset? Did it work? 
`
./redundans.py -v -i test/*_?.fq.gz -f test/contigs.fa -o test/run1
`
