### ISSUE TITLE
Redundans dockerfile

### ISSUE THREAD

**Issue by laure182** [Gabaldonlab/redundans#46]
Hello,
is it possible to get the redundans dockerfile somewhere ? I'm not looking for the image only as it is available on the dockerhub, but the dockerfile itself.
Our cluster architecture requires that we provide some modifications to the dockerfile in order to deploy the tools.
Best Regards

**Comment by lpryszcz** [comment]
Hi, you can find it in https://github.com/lpryszcz/docker/tree/master/redundans
