### ISSUE TITLE
test fails on new install

### ISSUE THREAD

**Issue by insectnate** [Gabaldonlab/redundans#52]
New user here.
Installed redundans and dependencies but when I try the test run
`./redundans.py -v -i test/*.fq.gz -f test/contigs.fa -o test/run1 -t 4`
I get this error. Not sure how to diagnose.  Any help appreciated.
Nathan

##################################################
[Thu Aug 23 14:52:58 2018] Reduction...
#file name	genome size	contigs	heterozygous size	[%]	heterozygous contigs	[%]	identity [%]	possible joins	homozygous size	[%]	homozygous contigs	[%]
test/run1/contigs.fa	163897	245	66377	40.50	221	90.20	94.854	0	97520	59.50	24	9.80

##################################################
[Thu Aug 23 14:52:59 2018] Estimating parameters of libraries...
 Aligning 19504 mates per library...
Insert size statistics				Mates orientation stats
FastQ files	read length	median	mean	stdev	FF	FR	RF	RR
test/5000_1.fq.gz test/5000_2.fq.gz	50	4998	4990.20	721.47	0	4674	0	0
test/600_1.fq.gz test/600_2.fq.gz	100	599	598.63	47.68	0	10000	0	0

##################################################
[Thu Aug 23 14:52:59 2018] Scaffolding...
 iteration 1.1: test/run1/contigs.reduced.fa	24	97520	39.355	17	94157	7321	2195	0	29603
Traceback (most recent call last):
  File "./redundans.py", line 541, in <module>
    main()
  File "./redundans.py", line 536, in main
    o.norearrangements, o.verbose, o.usebwa, o.log, o.tmp)
  File "./redundans.py", line 332, in redundans
    identity, overlap, minLength, resume)
  File "./redundans.py", line 129, in run_scaffolding
    sspacebin, verbose=0, usebwa=usebwa, log=log)
  File "/home/invasivespecies/redundans/bin/fastq2sspace.py", line 274, in fastq2sspace
    cores, mapq, upto, verbose, usebwa, log)
  File "/home/invasivespecies/redundans/bin/fastq2sspace.py", line 228, in get_tab_files
    proc = _get_aligner_proc(f1.name, f2.name, ref, cores, verbose, bwalog)
  File "/home/invasivespecies/redundans/bin/fastq2sspace.py", line 128, in _get_snap_proc
    subprocess.Popen(idxcmd.split(), stdout=log, stderr=log).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by lpryszcz** [comment]
Hi @insectnate , most likely you miss either SSPACE scaffolder or gapCloser. Could you double check all dependencies installed correctly?
