### ISSUE TITLE
DNA read seq length is too long.

### ISSUE THREAD

**Issue by arunprasanna83** [Gabaldonlab/redundans#54]
Hi,
I have pacbio reads and would like to perform redundans. I ran it with the following command:

` ./redundans.py -v -i /data/PACBIORAW/*.fastq.gz -o /data/output -t 20 -m 32 --log redudans_denovoassembly.log`

I get the following error:

> Platanus version: 1.2.4
> platanus assemble -tmp /tmp -t 20 -m 32 -o /data/ARUN/Canu_Redundans_Ambly/denovo/out -f /tmp/tmpZ30ny_ 
> Error(4): Read file exception!!
> DNA read seq length is too long.
> gzip: stdout: Broken pipe

How to solve this ?

Thanks,
AP

**Comment by lpryszcz** [comment]
Hi, de novo assembly mode only works for Illumina reads. Therefore if you want to run it with PacBio, you'll need to assemble PacBio reads into contigs and provide contigs to redundans using `-f contigs.fasta`.
