### ISSUE TITLE
gap closing only with PacBio reads

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#56]
Hi,
Is it possible to use gap closing with only PacBio reads?

Thank you in advance,

Michal

**Comment by bifxcore** [comment]
After some digging, I found this:

Redundans work-in-progress manual: Gap closing is facilitated through GapCloser. Redundans performs gap closing starting from libraries with the smallest insert size.

GapCloser manual: The GapCloser is designed to close the gaps emerging during the scaffolding processby SOAPdenovo or other assembler, using the abundant pair relationships of short
reads. 

So there it is: no input short reads, no gap closing!
