### ISSUE TITLE
Fixing assembly with polar_star

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#57]
Hi,
I discovered recently [polar_star](https://github.com/phasegenomics/polar_star). This tool takes your PacBio subreads (or in principle ONT reads), aligns them to your assembly, and breaks the assembly in places where long read coverage fluctuates.

Thank you in advance.

Michal

**Comment by lpryszcz** [comment]
That's really cool idea! I thought about that only it was rather complicated with short-reads. Again, I'd opt to implement it in newer version. Wanna give it a go? We'll discuss it via [our mailing list](https://groups.google.com/g/redundans)
