### ISSUE TITLE
redundancy reduction step alternative

### ISSUE THREAD

**Issue by mictadlo** [Gabaldonlab/redundans#58]
Hi,
Recently, [Purge Haplotigs](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2485-7) has been published and they did a comparison to your tool 

> Several tools have attempted to deal with this problem. The HaploMerger2 toolkit [14] and Redundans assembly pipeline [15] were designed to produce haplotype-fused assemblies from short-read sequences. However, the automated removal of contigs based only on alignments of contigs to each other without considering read depth of coverage may lead to repetitive and paralogous contigs being over-purged. Furthermore, resolving the haplotype sequences and producing a phased assembly has proven to be advantageous [16, 17]. Scripts available for use with long-read assemblies include; get_homologs.py, which uses sequence alignments to identify homologues and assist in manual curation [18] and HomolContigsByAnnotation, which uses gene annotations to match syntenic regions [19]. Each has its unique strengths and drawbacks, but both suffer from requiring manual reassignment of contigs by the user.

Do you have any plans to update/replace your redundancy reduction step?

Thank you in advance,

Michal

**Comment by mictadlo** [comment]
This [PR](https://github.com/lpryszcz/redundans/pull/59) could improve the above comments.

**Comment by lpryszcz** [comment]
Hi @mictadlo , thanks for the PR - it's definitely good idea! I'm starting to work on the update of Redundans and I'd definitely like to see that in new version, yet I'd keep current version as is for back-compatibility reasons. Let me know if you would like to contribute to the new version! 
Cheers,
