### ISSUE TITLE
Error after 'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by bioinfonm** [Gabaldonlab/redundans#6]
Morning,

  I was looking at using redundans for our current fungal genome project. I am running on OS X 10.11.6 with XCode installed. 

I keep getting this error: Error after 'generator' object has no attribute '__getitem__'

**after running this command:**
/usr/bin/python redundans.py -v -f tomentella_fuscocinerea_ray31_post_no_mito.fasta -r Thega1_AssemblyScaffolds_Repeatmasked.fasta -t 6

I think this has something to do with the generator returning an iterator but I am not sure. I still get a contigs files but not the reduced contigs. 

**Full error:**
[WARNING] Uneven line lengths in >contig-283000000
: 70,72,76,77,78,59,60
Traceback (most recent call last):
  File "redundans.py", line 495, in <module>
    main()
  File "redundans.py", line 490, in main
    o.norearrangements, o.verbose, o.log)
  File "redundans.py", line 293, in redundans
    minLength, threads, verbose=0, log=log)
  File "/Users/ara/Desktop/redundans/bin/fasta2homozygous.py", line 151, in fasta2homozygous
    contig2skip = fasta2skip(out, fasta, faidx, threads, identity, overlap, verbose)
  File "/Users/ara/Desktop/redundans/bin/fasta2homozygous.py", line 67, in fasta2skip
    sys.stderr.write(' [ERROR] `%s` (%s) not in contigs!\n'%(t, str(hits[i-1])))
TypeError: 'generator' object has no attribute '__getitem__'
Aras-MacBook-Pro:redundans ara$ lastal: write error

**Comment by lpryszcz** [comment]
Hi, the problem is ealier. You FastA file has uneven line length which causes problems. Make sure all seq lines has some max length ie 60 letter. You can do it using [fasta_formatter](http://hannonlab.cshl.edu/fastx_toolkit/commandline.html)

```
[WARNING] Uneven line lengths in >contig-283000000
: 70,72,76,77,78,59,60
```

**Comment by bioinfonm** [comment]
Great! Thank you!
