### ISSUE TITLE
Re-ordering contigs vs reference

### ISSUE THREAD

**Issue by joanmarticarreras** [Gabaldonlab/redundans#61]
Hi @lpryszcz ,

First, congratulations for your program / wrapper. It's the first that I found that it can be installed, run and the output is almost what I need. You would be surprised of how many scaffolders are out there and how badly mainteined they are.

Currently, I only have one request to enhance your program.

I work on a project of circular viruses, and after runnig an assembly with SPAdes, SKESA or Tadpole, it's always needed a round of redundans. Unfortunatley, the convention of start and end point of this circular virus is in a very-well assembled region, therefore even if I am capable to obtain the full-length genome of the virus, I am unable to linearize - out of the box - following the reference.

Would it be possible to know which options or if it can be implemented and option that would cut a contig if it maps to very distant parts of a genome (as for ciruclar genomes)?

Thank you a lot, and congratulations for Redundans. It works like a charm!

**Comment by lpryszcz** [comment]
Dear Joan, thanks a lot for very nice words! I don't think it's in the scope of Redundans to implement such feature. Nevertheless, have a look at https://github.com/rrwick/Unicycler - as far as I'm aware, it should be able to recognise and correctly create circular genomes. At least that's something my friends mentioned. 
Let me know if Unicycler doesn't work for you. I'll reconsider implementing such feature in Redundans then :) 
all the bests!
