### ISSUE TITLE
Reduction step "reduces" 90% of the assembly

### ISSUE THREAD

**Issue by SvitlanaLukicheva** [Gabaldonlab/redundans#62]
Hello,

I am working on a highly heterozygous genome which size is estimated to +/- 1.3Gb.

I have an assembly with a total length of 1.9 Gb, composed of 23k contigs and having 97% of complete BUSCOs. I ran Redundans (v. 0.13c) on this assembly using default parameters and after the reduction step I obtain only 16 contigs with a total length of 26 Mb. The complete pipeline finishes with 6 contigs with a total length of 20 Mb and 2.5% of complete BUSCOs.

I don't see any error message in the output. Maybe there is a way to modify some parameters to avoid reducing 90% of the assembly?

Thank you in advance!

**Comment by lpryszcz** [comment]
There are two possible explanations
- Your contigs are very short - Redundans skips contigs shorter than 200 nt (--minLength 200). 
- Your contigs have non-unique names - you can check with `grep -m50 ">" genome.fasta` or `grep ">" genome.fasta | sort | uniq -c | wc -l`

**Comment by SvitlanaLukicheva** [comment]
Thank you for your response!

Unfortunately, none of these explanations can explain my problem. Here are QUAST statistics on the contigs length:

```
# contigs | 23027
# contigs (>= 0 bp) | 23033
# contigs (>= 1000 bp) | 23018
# contigs (>= 5000 bp) | 22248
# contigs (>= 10000 bp) | 17910
# contigs (>= 25000 bp) | 10431
# contigs (>= 50000 bp) | 6441
```

And here is the result of grep command:
```
$ grep ">" gq.ctg.4th.fa | sort | uniq -c | wc -l
23033
```

**Comment by lpryszcz** [comment]
Could you send me the commands and full log please?

**Comment by SvitlanaLukicheva** [comment]
Hello, here is the command:

`./redundans.py -v -f ${ASSEMBLY_DIR}/gq.ctg.4th.fa -i ${ILLUMINA_DIR}/gq__illumina_250-500__R?.fastq -l ${ONT_DIR}/gq_nanopore.fastq -o $OUTPUT_DIR -t 16`

And below is the output:

[log.txt](https://github.com/lpryszcz/redundans/files/3232935/log.txt)

Thank you in advance for your help!

**Comment by forrwill** [comment]
> 
> 
> Hello,
> 
> I am working on a highly heterozygous genome which size is estimated to +/- 1.3Gb.
> 
> I have an assembly with a total length of 1.9 Gb, composed of 23k contigs and having 97% of complete BUSCOs. I ran Redundans (v. 0.13c) on this assembly using default parameters and after the reduction step I obtain only 16 contigs with a total length of 26 Mb. The complete pipeline finishes with 6 contigs with a total length of 20 Mb and 2.5% of complete BUSCOs.
> 
> I don't see any error message in the output. Maybe there is a way to modify some parameters to avoid reducing 90% of the assembly?
> 
> Thank you in advance

HI，could you please tell me where is the Redundans (v. 0.13c) ,I did not find it!

**Comment by wuxiaopei0509** [comment]
what's you input *.fasta file and the identity and overlap parameter?

**Comment by forrwill** [comment]
Thanks for your reply, there are two sources in github, another version is ok! thank you------------------ 原始邮件 ------------------
发件人: "wuxiaopei0509"<notifications@github.com>
发送时间: 2019年8月30日(星期五) 晚上9:09
收件人: "lpryszcz/redundans"<redundans@noreply.github.com>;
抄送: "Will"<1197364078@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [lpryszcz/redundans] Reduction step "reduces" 90% of the assembly(#62)



what's you input *.fasta file and the identity and overlap parameter?
 
&mdash;

**Comment by lpryszcz** [comment]
Hi @SvitlanaLukicheva , let me be necromancer. From your log it seems initially only 16 contigs were recognised in your assembly as unique. Either you have non-unique names for your contigs (check for space ie `contig1`, `contig2` etc is ok, but `contig 1`, `contig 2` will be reduced to `contig`) or the FastA file is corrupted in some other way. 
You can also remove FastA index (`.fai`) - if it's corrupted it can cause problems as well. 
Let me know if you managed to solve it! 

```
#file name      genome size     contigs heterozygous size       [%]     heterozygous contigs    [%]     identity [%]    possible joins  homozygous size [%]     homozygous contigs      [%]
/globalfs/ulb/ebe/slukiche/redundans__gq__wtdbg/contigs.fa      26438002        16      0       0.00    0       0.00    0.000   0       26438002        100.00  16      100.00
```
