### ISSUE TITLE
[WARNING] Nothing reduced, but why? Redundans seems to not process the entire fasta file.

### ISSUE THREAD

**Issue by DaniPaulo** [Gabaldonlab/redundans#63]
Hi everyone,

I am pretty new to Redundans and I am trying to perform the “Redundancy Reduction” step on a very heterozygous insect genome.

For that, I used the following command line:

redundans.py --verbose --noscaffolding --nogapclosing --fasta genome.fasta --identity 0.95 --overlap 0.66 --minLength 500 --threads 7 --outdir outdir --log genome.log

Please not that I used the "--noscaffolding" and "--nogapclosing" parameters, as I’m only interested in the Redundancy Reduction step of the pipeline.    

After some hours of run I got the following message: 

“[WARNING] Nothing reduced” 

My “.log” file looks like this:

#fname		contigs	bases	GC [%]	contigs>1kb 	bases>1kb 	N50	N90	Ns	longest
 		
genome.fasta	30	48147108	28.249	30	48147108	7306273	3975295	226300	13637223
contigs.fa		30	48147108	28.249	30	48147108	7306273	3975295	226300	13637223
contigs.reduced.fa	12	47642345	28.255	12	47642345	7306273	3975295	226300	13637223
scaffolds.reduced.fa	12	47642345	28.255	12	47642345	7306273	3975295	226300	13637223

What is very weird is that my genome has 17,817 scaffolds, but it seems that Redundans analyzed only 30 of them.

When I run the command grep -c ">" contigs.fa it returns to me “17817”, so it seems that the program is loading all contigs into the pipeline. 

So, what I guess is that redundans is working, but it’s not processing the entire fasta file and thus the assembly unchanged (as less than 1% of the contigs were reported in the “.log” file).

Any ideas of what is happening?

Thank you all for the help,
Dani.

**Comment by lpryszcz** [comment]
It's been dealt with through e-mail. The reason was not unique FASTA headers. Putting here for reference. 
There are two possible explanations: 
- Your contigs are very short - Redundans skips contigs shorter than 200 nt (--minLength 200). 
- Your contigs have non-unique names - you can check with `grep -m50 ">" genome.fasta`
