### ISSUE TITLE
Redundans seems to not be reading input Fasta properly

### ISSUE THREAD

**Issue by DaniPaulo** [Gabaldonlab/redundans#64]
Hi all,

I am trying to run the reduction step of Redundans in a genome with 17,817 scafolds and 1.4 Gb size. The problem is that Redundans seems to be reading only 30 scafolds and 48 Mb of it:

##################################################
[Sat Apr 13 15:25:47 2019] Reduction...
#file name	genome size	contigs	heterozygous size	[%]	heterozygous contigs	[%]	identity [%]	possible joins	homozygous size	[%]	homozygous contigs	[%]
contigs.fa	        48147108	30	688346	1.43	20	66.67	95.681	0	47458762	98.57	10	33.33

The interesting part is that when I grep -c ">" contigs.fa, it returns me the original 17,817 sequences.
Any Idea what is going wrong?

Thanks
Dani.

**Comment by lpryszcz** [comment]
That's been not-properly formatted FASTA (not unique headers).
