### ISSUE TITLE
INSTALL.sh uses but doesn't set $log

### ISSUE THREAD

**Issue by waoki** [Gabaldonlab/redundans#66]
INSTALL.sh appends `$log` to the current working directory and passes it to `.compile.sh`, but it never sets `$log`. This causes `.compile.sh` to fail, exiting at line 32, because on line 31 it attempted to redirect stdout to a directory instead of a file.

The user who reported the symptoms to me sent a screenshot; I've retyped it here instead of attaching a screenshot so that it is searchable. Apologies for any errors introduced in the process.

    Redundans and its dependencies will be installed in : /foo/redundans

    Installation will take 5-10 minutes.
    To track the installation status execute in the new terminal:
      tail -f /foo/redundans/

    I'll proceed with installation in10 seconds... Press Ctrl-C to cancel.

    Thu Apr 25 15:12:04 MDT 2019 Checking dependencies...
     Everything looks good :) Let's proceed...
    Thu Apr 25 15:12:04 MDT 2019 Downloading Redundans...
    Thu Apr 25 15:12:26 MDT 2019 Updating submodules...
    bin/.compile.sh: 8: bin/.compile.sh: cannot create /foo/redundans/: Is a directory
    bin/.compile.sh: 10: bin/.compile.sh: cannot create /foo/redundans/: Is a directory
    Thu Apr 25 15;12:26 MDT 2019 Compiling dependencies...
     === You can find log in: /foo/redundans/ ===
     I'll use 71 thread(s) for compiling
    Thu Apr 25 15:12:26 MDT 2019  Platanus
    bin/.compile.sh: 31: bin/.compile.sh: cannot create /foo/redundans/: Is a directory
      [2] ERROR!

**Comment by lpryszcz** [comment]
Hi, it's solved in the lastest version. Sorry for the problem!
