### ISSUE TITLE
Feature: Log file

### ISSUE THREAD

**Issue by apelin20** [Gabaldonlab/redundans#7]
Hello,

Just thought I would suggest a main log file that starts with the command issued and all parameters used. The log file would then be followed by all standard output the program generates.

As a little extra, you could also add the basic stats (n50, # contigs, longest contig) for both the input contigs and the output generated.

Adrian

**Comment by lpryszcz** [comment]
Thanks! I'll prepare.

**Comment by lpryszcz** [comment]
Added `--log` parameter in the new version
