### ISSUE TITLE
v0.13 version download

### ISSUE THREAD

**Issue by forrwill** [Gabaldonlab/redundans#71]
Hi, could you please tell me where is the v0.13 version. I just see the version 0.11

**Comment by forrwill** [comment]
> 
> 
> Hi, could you please tell me where is the v0.13 version. I just see the version 0.11

and I meet a question when I use fasta2homozygous.py sript，it report a error "Bus error (core dumped)"
![图片](https://user-images.githubusercontent.com/41096851/63562254-7d9dce80-c58f-11e9-840f-ba82db16e778.png)

**Comment by lpryszcz** [comment]
Hi @forrwill , that's peculiar error. What's your system?
