### ISSUE TITLE
ImportError After Launching

### ISSUE THREAD

**Issue by floutt** [Gabaldonlab/redundans#74]
Hello! I have been trying to get redundans running but have been dealing with one big issue. Whenever I try to run the program I get the following `ImportError`:

```
Traceback (most recent call last):
  File "/path/to/redundans/bin/redundans.py", line 36, in <module>
    from fasta2homozygous import fasta2homozygous
ImportError: No module named fasta2homozygous
```

I am currently running Python 2.7.12 and using the most recent version of redundans. I am not sure what could be causing the issue but it would be helpful to get feedback from others who may have had a similar issue. Thanks in advance!

**Comment by bifxcore** [comment]
@floutt did you try running redundans from the top directory, rather than the bin directory?
