### ISSUE TITLE
Redundans won't start

### ISSUE THREAD

**Issue by jahneldardavik** [Gabaldonlab/redundans#78]
I am trying brush up my PacBio assembly with redundans, but it won't start and I cannot figure out what is lacking. Any help is appreciated. Thanks.
Here is my call and the return from redundans:

/data/kvijed/tools/redundans-master/redundans.py -v -i /data/kvijed/IPN_Berry_New_Assemblies/bigAnitraR1.fastq /data/kvijed/IPN_Berry_New_Assemblies/bigAnitraR2.fastq -l /data/kvijed/Anitra2019/Anitra/PacBioAll.fastq -f /data/kvijed/Anitra2019/redundans/AnitraPilon24.fasta -t 12 -o /data/kvijed/IPN_Berry/redundansPacBio/anitra2019Redund
Traceback (most recent call last):
  File "/data/kvijed/tools/redundans-master/redundans.py", line 27, in <module>
    from fasta2homozygous import fasta2homozygous
  File "/data/kvijed/tools/redundans-master/bin/fasta2homozygous.py", line 20, in <module>
    from FastaIndex import FastaIndex
ImportError: No module named FastaIndex

**Comment by lpryszcz** [comment]
Hi, try `pip2 install fastaindex`. 
Btw, how were you installing the software? This should be installed automatically.
