### ISSUE TITLE
How is multiple redundancy handled?

### ISSUE THREAD

**Issue by tkatsuki** [Gabaldonlab/redundans#8]
How does the reduction step handle redundancy that involve more than 2 sequences? When mapped to itself, my assembly had some contigs that aligned to multiple other shorter contigs at high confidence (>99% identity, longer than 250nt, as showed in the attached image, which is actually after running fasta2homozygous.py). I want to remove all but the longest contig. When I ran redundans (only fasta2homozygous.py ), I saw messages like "matched already removed contig". Does this mean that redundans removes only the first matched sequence?

Thanks,

Takeo
![clipboard](https://cloud.githubusercontent.com/assets/3835653/10922488/3cea36ae-8230-11e5-933e-5ea54d68a439.png)

**Comment by lpryszcz** [comment]
Hi Takeo, In principle fasta2homozygous.py should remove all contigs but the longest one that fullfill identity & overlap critaria. Isn't it the case with your data? 
Don't bother about this message, it just means that some of the contigs have similarity to the contigs that were previously marked for removal. This is expected if you remove multiple overlapping contigs.
