### ISSUE TITLE
Not multiprocessing?

### ISSUE THREAD

**Issue by jwasmuth** [Gabaldonlab/redundans#8]
Hi,
This didn't seem to have been covered before. I'm running redundans with '-t 32' yet when I do a 'htop' to look at the processor usages, I see 32 instances of lastal being put through one processor. So they are being threaded through the one processor.

![image](https://user-images.githubusercontent.com/7673886/30083178-c161c222-924a-11e7-875a-30ab81be768b.png)

I did some speed tests with -t2 and -t32 and got no improvement in run time. I've tried two different systems with different linux os. Same problem.

When I run the lastal command at the commandline, I see the expected behaviour. My python skills are not particularly strong. I spoke with a colleague who said that getting python to run multiprocessor jobs can be a pain. Is there a problem?

Thanks

James

**Comment by lpryszcz** [comment]
Hi, It's not python problem, rather Last aligner. Make sure you have latest version - the safest is just cloning new copy

```
git clone --recursive https://github.com/lpryszcz/redundans.git
cd redundans && bin/.compile.sh
```
