### ISSUE TITLE
--log file empty, get statistics?

### ISSUE THREAD

**Issue by matryoskina** [Gabaldonlab/redundans#80]
Hello! 
First, thanks for the very nice program. It run on my diploid plant genome and I'm happy with the reduced.fa file. 
I set --log file to get info, but the file has been completely empty since I started the run (6 days ago - I run it on a SLURM cluster).
Is there a way to get the statistics after the reduction step, like heterozygosity %, without rerun the software??
Also, I would like to know which contigs have been removed from the original assembly. The only file is the hetero.tsv table with the contig list. Which contigs should I take into account?
Thanks

**Comment by lpryszcz** [comment]
Hi @matryoskina , thanks, I'm glad you find it useful :)  
You can find answers to most of your questions [in here](https://github.com/lpryszcz/redundans/tree/master/test#reduction).  

As for the log output, the only thing that comes to my mind is the buffering of writes by Python. Maybe don't use --log and check stderr and stdout of your job in SLURM? Although those outputs can be also buffered. 
Alternatively try interactive run. 

Hope it helps!
