### ISSUE TITLE
why  -i fq is required？

### ISSUE THREAD

**Issue by rainjy** [Gabaldonlab/redundans#83]
wget the release 0.11-beta and 0.11c , but the script (redundans.py) isn't same to the webpage, and 
 cmd:  python2 redundans.py -v -f test_more_than300bp.fasta -o ./tmp -t 8 --identity 0.95 --overlap 0.9 --noscaffolding --nogapclosing --log log.txt
error: argument -i/--fastq is required
I just want to eduction using assembled contigs, thank you!

**Comment by lpryszcz** [comment]
hi, please try more recent version (v0.14a is the latest). 
btw, if you want to run only reduction step, you can call bin/fasta2homozygous.py directly using the same parameters.
