### ISSUE TITLE
Assembly correction 

### ISSUE THREAD

**Issue by mamtamasand** [Gabaldonlab/redundans#84]
Hello everyone
I am trying to assemble 1.3Gb genome with 1.2% heterozygosity. I have done the hybrid assembly with masurca which resulted to overestimated assembly, the i ran redundans program which gives the assembly of 1GB, reduced size from actual genome size. In the result folders there are two corrected files, intially i got the 1.4GB assembly with gap closing with long reads and after that 1GB with mapping short reads. My question is,  Can I use the 1.4GB assembly named as scaffolds.longreads.1.fa for downstream data analysis, because I am worried that in final 1GB assembly from redundans i will miss the gene models.
Please suggest the more appropriate way.
Thank You in advance

**Comment by lpryszcz** [comment]
Hi, have you used long reads with redundans? 

yes, you can definitely use the scaffolds.longreads.1.fa. Just keep in mind that it skips the last reduction step. Still, the initial heterozygous contigs should be removed before scaffolding.

**Comment by mamtamasand** [comment]
ok
Thank You
