### ISSUE TITLE
Change of tmp default folder

### ISSUE THREAD

**Issue by marco91sol** [Gabaldonlab/redundans#85]
Hi, 

I launched the following command: 

~/Software/redundans/redundans.py -t 64 -i *fastq -f assembly.fasta --reference related_genome.fna --log redundans.log -o redundans_output2 --tmp ./redundas_tmp -m 128 

However, it continues to put temporary files in the /tmp folder. 

How can I solve it? 
Marco

**Comment by lpryszcz** [comment]
Hi @marco91sol , which files are stored in /tmp? Can you please also attach the log?
