### ISSUE TITLE
Confusing or misleading run text

### ISSUE THREAD

**Issue by pdimens** [Gabaldonlab/redundans#86]
Hello! First and foremost I would like to gush about how wonderful redundans is. Thank you so much for putting it together and continuing to maintain it.

I would like to address a possible bug or misunderstanding. I run redundans using the `--noscaffolding` and `--nogapclosing` parameters, and this is what the run text reads:
```
Options: Namespace(fasta='Abyss/geno-contigs.fa', fastq=['BFT_all.R1.fq.gz', 'BFT_all.R2.fq.gz'], identity=0.51, iters=2, joins=5, limit=0.2, linkratio=0.7, log=<open file '<stderr>', mode 'w' at 0x7f45f74f61e0>, longreads=[], mapq=10, mem=125, minLength=200, nocleaning=True, nogapclosing=False, norearrangements=False, noreduction=True, noscaffolding=False, outdir='redundans_1', overlap=0.8, reference='', resume=True, threads=20, tmp='/tmp', usebwa=True, verbose=True)
```

Notably, I see:
- `nogaplosing=False`  (should be true?)
- `noreduction=True`   (should be false?)
-  `noscaffolding=False` (should be true?)

**Comment by lpryszcz** [comment]
Hi @pdimens , thanks for spotting the nonsense in the code and all the nice words :) I will resolve it in the next release, which I've been thinking for a while now.
