### ISSUE TITLE
scaffolding options

### ISSUE THREAD

**Issue by bishopia** [Gabaldonlab/redundans#87]
Hi there,

I have a question about deciding between various read libraries for the scaffolding step in your pipeline. My input into your pipeline is a SPAdes hybrid assembly that used PE150 reads and PacBio CCS reads (see first set of metrics below). My intention was to use the CCS reads for scaffolding, but I also have reanalyzed the returned PacBio reads to achieve a lower median quality of the dataset but many more reads, something in between the consensus CCS reads and the original subreads (ccs --all mode). A quick summary of both look like this:

file | format | type | num_seqs | sum_len | min_len | avg_len | max_len | N50 | Q20(%) | Q30(%)
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
CCS | FASTQ | DNA | 1,328,116 | 17,904,868,613 | 45 | 13,481.4 | 46,208 | 13,722 | 98.99 | 97.64

file | format | type | num_seqs | sum_len | min_len | avg_len | max_len | N50 | Q20(%) | Q30(%)
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
CCS_LQ | FASTQ | DNA | 3,235,048 | 46,409,419,253 | 13 | 14,345.8 | 463,181 | 14,889 | 44.11 | 42.19

Do you think the larger but worse quality CCS_LQ library would improve redundans output? Or maybe it would but at the cost of quality reduction in the contigs themselves through some sort of consensus calling in the overlap section during scaffolding? Would that may lead to mosaic of lower and higher quality sequence between the contigs and the scaffold sections? I'm not that clear on scaffolding generally so any thoughts here would be very helpful. Thanks!

**Comment by lpryszcz** [comment]
Dear @bishopia , thanks for the interest in redundans. 
As for your question, the accuracy of your read doesn't matter that much for redundans scaffolding (it should work with reads that are 80% identical to the reference), as long as you don't have reads that are obviously wrong ie read fusions. 
But, the long-read scaffolding is still somewhat experimental (I've never quite manage to push it into production), so please treat it as such. 
If you experience any problems with long-read scaffolding, you could try to use some external long-read scaffolder and run redundans with SPAdes contigs (-f) and scaffolds from long reads as a reference (-r). 
Hope it helps.
