### ISSUE TITLE
Where is the `fasta2diverged.py` script?

### ISSUE THREAD

**Issue by MatteoSchiavinato** [Gabaldonlab/redundans#92]
Hi, 
I am trying to follow your workflow in [Pryszcz et al., 2016](https://academic.oup.com/nar/article/44/12/e113/2457531?login=true#87015117) but I can't find in the repository the `fasta2diverged.py` script that you mention in the paper (neither here, nor in gabaldonlab/redundans). 

Would it be possible to have that script? 

Thanks!

**Comment by Dfupa** [comment]
Hi Matteo,

You can find the  `fasta2diverged.py` script [here](https://github.com/lpryszcz/bin). Let me know if you need anything more and I'll reopen the issue
