### ISSUE TITLE
Gapcloser step no multithread

### ISSUE THREAD

**Issue by aabaricalla** [Gabaldonlab/redundans#94]
Hi!
I'm currently using Redundans, but when I was testing it I found that the Gapcloser step doesn't use the multithread option even when the option is provided.
Any suggestion?
![image](https://user-images.githubusercontent.com/19737062/186043407-66fbe051-e5f7-4e3a-a866-4245191794a5.png)

**Comment by aabaricalla** [comment]
Hi again, I'm dealing with the same problem with Lastal as issue #79 already reported.

**Comment by lpryszcz** [comment]
Hi @aabaricalla  , yes, it seems certain steps in GapCloser are not multi-threaded... 
note we're working on the app update, so we'll try to replace GapCloser in the new version.
