### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by BioHlT** [Gabaldonlab/redundans#95]
Hello 

I encountered an error while running redundans.py 
python2 ./redundans.py -f Mayorella.pilon3.fasta -o assembly_redundans_out_2 --identity .95 --overlap 0.95 -i YT24_Mayorella_R1.trimmomatic.fasta YT24_Mayorella_R2.trimmomatic.fasta --usebwa 1> redundans.log 2>&1

redundans.log 

assembly_redundans_out_2/contigs.fa	37072690	3531	11281563	30.43	464	13.14	99.212	0	25791127	69.57	3067	86.86
Insert size statistics				Mates orientation stats
FastQ files	read length	median	mean	stdev	FF	FR	RF	RR
YT24_Mayorella_R1.trimmomatic.fasta YT24_Mayorella_R2.trimmomatic.fasta	149	298	306.49	83.29	23	9896	59	22
   5158226 pairs. 2409542 passed filtering [46.71%]. 45882 in different contigs [0.89%].
   5158226 pairs. 2409566 passed filtering [46.71%]. 45898 in different contigs [0.89%].
Traceback (most recent call last):
  File "/Users/teklelab/Documents/Softwares/redundans/redundans.py", line 541, in <module>
    main()
  File "/Users/teklelab/Documents/Softwares/redundans/redundans.py", line 536, in main
    o.norearrangements, o.verbose, o.usebwa, o.log, o.tmp)
  File "/Users/teklelab/Documents/Softwares/redundans/redundans.py", line 384, in redundans
    resume = run_gapclosing(outdir, libraries, outfn, lastOutFn, threads, limit, iters, resume, verbose, log)
  File "/Users/teklelab/Documents/Softwares/redundans/redundans.py", line 240, in run_gapclosing
    GapCloser = subprocess.Popen(cmd, stdout=gapcloselog, stderr=gapcloselog)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

I saw the previous post with a similar error suggesting checking if all the dependencies are present. I have used redundans for other species and it only fails for this Species. I am curious as to why that is. 

I would appreciate any help.

P.S I have run preprocess.py to clean my fasta file but came back with the same error.

**Comment by lpryszcz** [comment]
hi, the error happens during gap closing `GapCloser = subprocess.Popen(cmd, stdout=gapcloselog, stderr=gapcloselog)`. Can you make sure GapCloser is in your path? 

> P.S I have run preprocess.py to clean my fasta file but came back with the same error.

What does `preprocess.py` do?

**Comment by BioHlT** [comment]
Hi
preprocess.py preprocess FASTA file, outputs a clean FASTA, and separates contigs based on unique headers. It also removes special characters.

I have checked GapCloser is in my path and works on other species.

**Comment by Dfupa** [comment]
This issue is marked as stale by the stale_bot.
