### ISSUE TITLE
redundant running too long time

### ISSUE THREAD

**Issue by zhang144999** [Gabaldonlab/redundans#96]
Dear Developer

I am using 'redundant' running my assemble genome.
I am using different parameters running twice, including reduce the cover identity value.
The survey shows this species genome have 17.5G, but I using hifiasm getting 21.5G, using 33* hifi data and 10* hic data, this is the best version for assemble now.
I guess hifiasm step can not remove redundancy clearly. 
Now, The redundant also running, It ran for about half a month. I think this must be not final running 'redundant'.
Until now, there is no result.
So, could you give me some advice for me how to accelerate the program?

Best 
Zhang～

**Comment by Dfupa** [comment]
Hi Zhang,

I've never heard of anyone trying Redundans on such a large genome (17.5 - 21.5 GB!!!). We are currently working on the next Redundans release and we are aiming to improve significantly the performance. Based on previous issues ( #82 ), it should be able to finish, but it might take longer that the other user's case (40 days for a 7.2 GB genome). Unless you are able to keep the job computing for more than a month, you might want to wait till we drop the next release.

**Comment by lpryszcz** [comment]
Totally second to that! @zhang144999 you have the hell of the assembly to work with... What's your N50 and number of contigs?
In the first step, redundans will calculate all-vs-all alignments between your contigs using LASTal. LASTal is very sensitive, but it won't be very fast. 
I guess in the future LASTal could be optionally replaced with minimap2 if the user doesn't need high sensitivity (ie minimap2 should work well for >90%). 
Unfortunately, at this point we can't do much to help.

**Comment by zhang144999** [comment]
> Totally second to that! @zhang144999 you have the hell of the assembly to work with... What's your N50 and number of contigs?
> In the first step, redundans will calculate all-vs-all alignments between your contigs using LASTal. LASTal is very sensitive, but it won't be very fast.
> I guess in the future LASTal could be optionally replaced with minimap2 if the user doesn't need high sensitivity (ie minimap2 should work well for >90%).
> Unfortunately, at this point we can't do much to help.

Honestly, assembly is not a difficult for me, I using hifiasm 3 days can build this genome primary contigs.
After add 10* hic data, latest version genome is 5400 contigs, N50 is 19M. It's looks like fine. But this also more bigger than our survey. I even began to question the accuracy of the survey data.
I using PASA to get true transcripts, minimap2 as aligner. It's can't running, I saw PASA developer say minimap2 is not suitable on big genome(They claim the latest version of PASA has been fixed, but I still can't run it) , but gmap is good. Maybe you can refer to my experience.
Now, I check the background job, 'LASTal' and python2 are running alternate.
The job still in step one.
It's ok, I will wait for it to run. 
let's see what that happen.

Best~
Zhang
