### ISSUE TITLE
SSPACE_Standard_v3.0.pl run failed with Can't open bwa output -- fatal 

### ISSUE THREAD

**Issue by NailouZhang** [Gabaldonlab/redundans#97]
Hi,
I try scaffold contigs with SSPACE_Standard_v3.0.pl and follow paraments,
"libraries.txt "
"Lib1 bowtie R_1.fastq R_2.fastq 166 0.5 FR "
"SSPACE_Standard_v3.0.pl -l libraries.txt -s contig.fasta -x 1 -T 45 -b standard_out"
Run log,
SSPACE_Standard_v3.0.pl -l libraries.txt -s contig.fasta -x 1 -T 45 -b standard_out
Your inserted inputs on [SSPACE_Standard_v3.0_linux] at Sun Feb 5 09:11:39 2023:
Required inputs:
-l = libraries.txt
Number of paired files = 1
-s = contig.fasta
-b = standard_out

Optional inputs:
-x = 1
-z = 0
-k = 5
-g = 0
-a = 0.7
-n = 15
-T = 45
-p = 0

Contig extension inputs:
-o = 20
-m = 32
-r = 0.9

=>Sun Feb 5 09:11:39 2023: Reading, filtering and converting input sequences of library file initiated

=>Sun Feb 5 09:14:31 2023: Extending of contigs with unmapped reads

=>Sun Feb 5 09:14:31 2023: Building Bowtie index for contigs

=>Sun Feb 5 09:14:31 2023: Mapping reads to contigs with Bowtie
Thread 53 terminated abnormally: Can't open bwa output -- fatal
Thread 54 terminated abnormally: Can't open bwa output -- fatal
Thread 55 terminated abnormally: Can't open bwa output -- fatal
Thread 56 terminated abnormally: Can't open bwa output -- fatal
Thread 57 terminated abnormally: Can't open bwa output -- fatal
Thread 58 terminated abnormally: Can't open bwa output -- fatal
Thread 59 terminated abnormally: Can't open bwa output -- fatal

Process 'extend/format contigs' failed on Sun Feb 5 11:30:05 2023

########################################
what's more, I find this seem a common issue with SSPACE_Standard, such as,
https://www.biostars.org/p/432937/;
https://www.researchgate.net/post/Question_SSPACE_Bowtie_error_cant_open_bwa_output--fatal;
https://www.seqanswers.com/forum/bioinformatics/bioinformatics-aa/50398-problem-with-sspace-multi-threading-and-memory-restrictions;

Can you help me solve this problem?

Nailou Zhang

**Comment by NailouZhang** [comment]
I found that by setting the thread parameters to default, the program would work well.

**Comment by lpryszcz** [comment]
thank you for reporting this!
