### ISSUE TITLE
Docker/singularity container

### ISSUE THREAD

**Issue by aabaricalla** [Gabaldonlab/redundans#99]
Hola a todos!
I saw the recent update of redundans, the conda or docker update is ready to download?
I'm really excited about the improvements of this program.

**Comment by Dfupa** [comment]
Hi aabaricalla!

The bioconda recipe is still a **WIP**, the docker image from [docker hub](https://hub.docker.com/repository/docker/cgenomics/redundans) is updated to the new version. Please let us now if you encounter any issue!

**Comment by Dfupa** [comment]
This issue is marked as stale by the stale_bot.
